# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3baa2d68dfb01a2d944c115cb703fff879418bb8118383c0efc217c1cfb3eabe31f02a4c3428a84efa72bf055bffbb98b3b24a51f67a22a59fd7d157392b2de

test:
  secret_key_base: 898d8f292215e163ee222d0af27889a22dfbef3e6be5a6fee3ab7beed033ede83704dd1886c81fcd87d05d166bf1e49f6dd4836a0354f7172d1def4bfc893f49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
